### PR TITLE
Classname prop

### PR DESCRIPTION
**Pull request by TravisBallard**
This allows me to pass in a `css` prop so i can style the ul with emotion. 

usage: 

```
  const paginationCss = css`
    list-style: none outside;
    text-align: center;
    
    li {
      display: inline-block;
    }
  `;

  return (
      <Pagination
        items={items}
        action={action}
        postsPerPage={postsPerPage}
        css={paginationCss}
      />
  );
```

### CODE REVIEW

**Comment by TravisBallard** [comment]
should note that the base branch for this was semantic-output as i forgot to switch back to master before starting. after you merge #5, it will probably cause some conflicts. you can close #5 and merge this one (if you approve) instead since it has the same code.

**Comment by dane-brown** [comment]
@TravisBallard Would you be able to pull master again and just re-apply the extra prop?

**Comment by TravisBallard** [comment]
@dane-brown I pulled down master and re-applied the prop and made a new PR for it.

**Comment by TravisBallard** [comment]
Closed in favor of #11

**Pull request closed without merging**
